### ISSUE TITLE
horizontal splitter?

### ISSUE THREAD

**Issue by jianhuiz** [rmp135/vue-splitter-comp#1]
any plans to horizontal splitting?

**Comment by rmp135** [comment]
I wasn't planning on it. I'll keep the ticket open in case anyone wants to make a PR.

**Comment by rmp135** [comment]
Had some time to spare and implemented this feature. You can find it in version 1.3.0.

**Comment by jianhuiz** [comment]
cool. 
could you support initial position config, instead of default to 50%?
