### ISSUE TITLE
Configurable default percentage

### ISSUE THREAD

**Issue by neithere** [rmp135/vue-splitter-comp#3]
Currently I have to do this:
```
created () {
  this.$refs.splitter.percent = 20
}
```
Not only is this ugly, but also clicking the splitter resets the percentage to 50, not 20.

It would be nice to have it configurable via a simple prop.

Thanks!

**Comment by rmp135** [comment]
Added in v1.4.0. Use optional prop `defaultPercent` to set the initial / reset percentage.
